//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.261
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSocial {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedSocial.StringsResource", typeof(StringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AjDMu4GZbEKMUDkzf9YsndSaA49708fwwj_48vd0HbnKLUE99gn-k4TJXYFcevIC.
        /// </summary>
        internal static string BingId {
            get {
                return ResourceManager.GetString("BingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error while check user credentials.
        /// </summary>
        internal static string ErrorLogin1 {
            get {
                return ResourceManager.GetString("ErrorLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name is not correct.
        /// </summary>
        internal static string ErrorLogin2 {
            get {
                return ResourceManager.GetString("ErrorLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password does not match.
        /// </summary>
        internal static string ErrorLogin3 {
            get {
                return ResourceManager.GetString("ErrorLogin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checking user....
        /// </summary>
        internal static string ErrorLoginTitle {
            get {
                return ResourceManager.GetString("ErrorLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User already exists, please try with another username.
        /// </summary>
        internal static string ErrorRegister1 {
            get {
                return ResourceManager.GetString("ErrorRegister1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error while registering user.
        /// </summary>
        internal static string ErrorRegister2 {
            get {
                return ResourceManager.GetString("ErrorRegister2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User created successfully, please login.
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creating user....
        /// </summary>
        internal static string UserCreatedTitle {
            get {
                return ResourceManager.GetString("UserCreatedTitle", resourceCulture);
            }
        }
    }
}
